CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

//CONFIG_ZMK_USB_LOGGING=y

//CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000
//CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
//CONFIG_INPUT_LOG_LEVEL_DBG=y
//CONFIG_PMW3610_LOG_LEVEL_DBG=y